<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ParqueosBaulerasSeeder extends Seeder
{
    public function run(): void
    {
        $propiedades = [
            // SOTANO 4
            // Parqueos y Parqueos con Baulera
            ['codigo' => 'P-125-118', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 100.00],
            ['codigo' => 'P-114', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-115', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-116', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-117', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-113', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-112', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-111', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-110', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-109', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-108', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-107', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-106', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'PB-104-76', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 18.31],
            ['codigo' => 'P-103', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-102', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'PB-101-68', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 36.44],
            ['codigo' => 'P-100', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'PB-99-57', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 19.66],
            ['codigo' => 'PB-98-95', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 19.34],
            ['codigo' => 'PB-97-94', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 32.01],
            ['codigo' => 'P-96', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-95', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-94', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 12.50],

            // Bauleras Sotano 4
            ['codigo' => 'B-93', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 4.50],
            ['codigo' => 'B-92', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.53],
            ['codigo' => 'B-91', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.76],
            ['codigo' => 'B-90', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.76],
            ['codigo' => 'B-89', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.53],
            ['codigo' => 'B-88', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.53],
            ['codigo' => 'B-87', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.53],
            ['codigo' => 'B-86', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.76],
            ['codigo' => 'B-85', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.99],
            ['codigo' => 'B-84', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 6.14],
            ['codigo' => 'B-83', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.53],
            ['codigo' => 'B-82', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.53],
            ['codigo' => 'B-81', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.53],
            ['codigo' => 'B-80', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 7.96],
            ['codigo' => 'B-79', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.02],
            ['codigo' => 'B-78', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.01],
            ['codigo' => 'B-77', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.68],
            ['codigo' => 'B-75', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 4.74],
            ['codigo' => 'B-74', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 4.32],
            ['codigo' => 'B-73', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 4.32],
            ['codigo' => 'B-72', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 4.74],
            ['codigo' => 'B-71', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 7.20],
            ['codigo' => 'B-70', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 4.70],
            ['codigo' => 'B-69', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.34],
            ['codigo' => 'B-67', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 9.10],
            ['codigo' => 'B-66', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 4.23],
            ['codigo' => 'B-65', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 4.86],
            ['codigo' => 'B-64', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 4.77],
            ['codigo' => 'B-63', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 6.50],
            ['codigo' => 'B-62', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 8.56],
            ['codigo' => 'B-61', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.51],
            ['codigo' => 'B-60', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.50],
            ['codigo' => 'B-59', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.49],
            ['codigo' => 'B-58', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 4', 'metros_cuadrados' => 5.84],

            // SOTANO 3
            // Parqueos Sotano 3
            ['codigo' => 'P-93', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-92', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-91', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-90', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-89', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-88', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-87', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-86', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-85', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-84', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-83', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-82', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-81', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-80', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 25.00],
            ['codigo' => 'P-79', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-78', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-77', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-76', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-75', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-74', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'PB-73-300', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 24.10],
            ['codigo' => 'P-72', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-71', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-70', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-69', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-68', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-67', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-66', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-65', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-64', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-63', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 12.50],

            // Bauleras Sotano 3
            ['codigo' => 'B-56', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.57],
            ['codigo' => 'B-55', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.57],
            ['codigo' => 'B-54', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.57],
            ['codigo' => 'B-53', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.57],
            ['codigo' => 'B-52', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.51],
            ['codigo' => 'B-51', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.62],
            ['codigo' => 'B-50', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.57],
            ['codigo' => 'B-49', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.57],
            ['codigo' => 'B-48', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.57],
            ['codigo' => 'B-47', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.51],
            ['codigo' => 'B-46', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.57],
            ['codigo' => 'B-45', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 18.78],
            ['codigo' => 'B-44', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 7.38],
            ['codigo' => 'B-43', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 7.62],
            ['codigo' => 'B-42', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 7.62],
            ['codigo' => 'B-301', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 10.67],
            ['codigo' => 'B-40', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.52],
            ['codigo' => 'B-41', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 3', 'metros_cuadrados' => 5.62],

            // SOTANO 2
            // Parqueos Sotano 2
            ['codigo' => 'P-62', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-61', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-60', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-59', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-58', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-57', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-56', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-55', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-54', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-53', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-52', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-51', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-50', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-49', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-48', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-47', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-46', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-45', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-44', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'PB-43-11', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 20.27],
            ['codigo' => 'PB-42-12', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 20.61],
            ['codigo' => 'PB-41-13', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 20.40],
            ['codigo' => 'PB-40-14', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 20.67],
            ['codigo' => 'PB-39-15', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 23.39],
            ['codigo' => 'P-38', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-37', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-36', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 25.00],
            ['codigo' => 'P-35', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-34', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-33', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-32', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 12.50],

            // Bauleras Sotano 2
            ['codigo' => 'B-39', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 5.91],
            ['codigo' => 'B-38', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 5.80],
            ['codigo' => 'B-37', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 21.17],
            ['codigo' => 'B-36', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 5.27],
            ['codigo' => 'B-35', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.82],
            ['codigo' => 'B-34', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.74],
            ['codigo' => 'B-33', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.32],
            ['codigo' => 'B-32', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.74],
            ['codigo' => 'B-31', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.32],
            ['codigo' => 'B-30', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 5.34],
            ['codigo' => 'B-29', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.70],
            ['codigo' => 'B-28', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 7.80],
            ['codigo' => 'B-27', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 9.28],
            ['codigo' => 'B-26', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.15],
            ['codigo' => 'B-25', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.76],
            ['codigo' => 'B-24', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.03],
            ['codigo' => 'B-23', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.19],
            ['codigo' => 'B-22', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.88],
            ['codigo' => 'B-21', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 4.70],
            ['codigo' => 'B-20', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 6.13],
            ['codigo' => 'B-19', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 5.51],
            ['codigo' => 'B-18', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 5.50],
            ['codigo' => 'B-17', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 5.49],
            ['codigo' => 'B-16', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 5.84],
            ['codigo' => 'B-10', 'tipo_propiedad_id' => 2, 'ubicacion' => 'Sotano 2', 'metros_cuadrados' => 9.35],

            // SOTANO 1 - Parqueo Público
            ['codigo' => 'P-1', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Sotano 1', 'metros_cuadrados' => 899.10],

            // PLANTA 1 - Parqueos
            ['codigo' => 'P-5', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Planta 1', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-6', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Planta 1', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-13', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Planta 1', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-126', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Planta 1', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-127', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Planta 1', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-128', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Planta 1', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-129', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Planta 1', 'metros_cuadrados' => 12.50],
            ['codigo' => 'P-130', 'tipo_propiedad_id' => 1, 'ubicacion' => 'Planta 1', 'metros_cuadrados' => 12.50],
        ];

        foreach ($propiedades as $propiedad) {
            DB::table('propiedades')->insert([
                'codigo' => $propiedad['codigo'],
                'tipo_propiedad_id' => $propiedad['tipo_propiedad_id'],
                'ubicacion' => $propiedad['ubicacion'],
                'metros_cuadrados' => $propiedad['metros_cuadrados'],
                'activo' => true,
                'observaciones' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}